config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    resources :apps
    resources :invitations, only: [:new, :create]
  end

  root 'pages#index'

  devise_for :users
  resources :invitation_requests, only: [:create,:new]
  namespace :api do
    resources :apps ,only:[:create, :update, :destroy, :index]
    post "/login" => 'users#login'
  end
end

app/views/pages/index.html.erb
<div id="main-content" style="width: 100%; height: 441px; background-color: #2499A6">
  <h1 class="text-center" style="margin-top: 0; padding-top: 80px; font-weight: 600; color: white; font-size: 45px;">Love Heroku? Want to stay free and 24/7 available?</h1>
  <h3 class="text-center" style="color: white; font-weight: 400; margin-bottom: 50px;">We help you setup so you can stay free and available forever. Learn More.</h3>
  <div class="text-center">

    <%= link_to "REQUEST AN INVITE", new_invitation_request_path,
      class: "btn btn-default btn-request-invitation" %>

  </div>
</div>

<div id="main-info" style="width: 100%; height: 350px">
  <h2 class="text-center" style="padding-top: 80px">We've heard the news and we've come with a solution</h2>
  <hr style="margin: 35px 500px; border: solid 2px black; border-radius: 10px">
  <h4 class="text-center" style="margin: 0 300px">Heroku has released new tiers where free features are becoming thinner and thinner. We provide a solution by helping you switch easily between two servers, and therefore helping you maintain free forever.</h4>
</div>

<div id="features" style="width: 100%; height: 550px; background-color: #146973; color: white">
  <div class="container">
    <h2 class="text-center" style="color: white; padding-top: 100px">Awesome Features</h2>
    <hr style="margin: 20px 500px; border: solid 2px white; border-radius: 10px">
    <div class="row text-center" style="margin-bottom: 60px">
      <div class="col-md-4">
        <i class="fa fa-4x fa-paper-plane text-primary"></i>
        <h3>Easy setup</h3>
        <h4>Getting started with TherokuBalance is fast and easy. No difficult configuration options. We think that simple is better.</h4>
      </div>
      <div class="col-md-4">
        <i class="fa fa-4x fa-diamond text-primary"></i>
        <h3>Command line tool</h3>
        <h4>Just download the <a href="https://rubygems.org/gems/theroku">theroku gem</a>. Accelerate your workflow by using your terminal.</h4>
      </div>
      <div class="col-md-4">
        <i class="fa fa-4x fa-globe text-primary"></i>
        <h3>Crafted with love</h3>
        <h4>This is a project made by developers for developers. We believe in global solutions for programmers' problems.</h4>
      </div>
  </div>
  </div>
</div>