config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    resources :apps
    resources :invitations, only: [:new, :create]
  end

  root 'pages#index'

  devise_for :users
  resources :invitation_requests, only: [:create,:new]
  namespace :api do
    resources :apps ,only:[:create, :update, :destroy, :index]
    post "/login" => 'users#login'
  end
end

app/views/apps/_apps_navigation.html.erb
<div class="list-group">
  <%= link_to apps_path, class: "list-group-item #{'active' if ['index','create'].include?(params[:action]) }" do %>
    <span class="glyphicon glyphicon-plus pull-right"></span>
    New App
  <% end %>
  <% @apps.each do |a| %>
    <%= link_to edit_app_path(a), class: "list-group-item #{'active' if @app == a }" do %>
      <span class="glyphicon glyphicon-chevron-right pull-right"></span>
      <%= a.subdomain %>
    <% end %>
  <% end %>
</div>

app/views/apps/_form.html.erb
<%= simple_form_for(@app) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <label class="col-sm-3" for="subdomain">TheRokuBalance Subdomain</label>
    <div class="input-group input-group-lg col-sm-9">
      <span class="input-group-addon">http://</span>
      <%= f.input :subdomain, placeholder: "app-name", wrapper: false, class: "form-control", label: false %>
      <span class="input-group-addon input-group-addon-suffix">therokubalance.com</span>
    </div>
  </div>
  <div class="form-group">
    <label for="url1" class="col-sm-3">Heroku app url 1</label>
    <div class="input-group input-group-lg col-sm-9">
      <span class="input-group-addon">http://</span>
      <%= f.input :url1, placeholder: "url1", wrapper: false, class: "form-control", label: false %>
      <span class="input-group-addon input-group-addon-suffix">herokuapp.com</span>
    </div>
  </div>
  <div class="form-group">
    <label for="subdomain" class="col-sm-3">Heroku app url 2</label>
    <div class="input-group input-group-lg col-sm-9">
      <span class="input-group-addon">http://</span>
      <%= f.input :url2, placeholder: "url2", wrapper: false, class: "form-control", label: false %>
      <span class="input-group-addon input-group-addon-suffix">herokuapp.com</span>
    </div>

  </div>

  <div class="form-group pull-right">
    <%= f.button :submit, class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="title-wrapper">
        <h3>My Apps</h3>
      </div>
      <%= render "apps/apps_navigation" %>
    </div>
    <div class="col-xs-6 col-md-9">
      <div class="title-wrapper">
        <%= link_to app_path(@app),
            class: "btn btn-xs btn-danger pull-right",
              method: :delete,
              data: { confirm: "Are you sure you want to delete #{@app.subdomain}?" } do %>
          Delete
        <% end %>
        <div class="title-wrapper">
          <h2>Editing <strong><%= @app.subdomain %></strong> </h2>
        </div>
        <%= render "apps/form" %>
      </div>
    </div>
  </div>
</div>

app/views/apps/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="title-wrapper">
        <h3>My Apps</h3>
      </div>
      <%= render "apps/apps_navigation" %>
    </div>
    <div class="col-xs-6 col-md-9">
      <div class="title-wrapper">
        <h3>App registration</h3>
      </div>
      <%= render "apps/form" %>
    </div>
  </div>
</div>

app/views/apps/new.html.erb
<h2>App registration</h2>

<%= simple_form_for(@app) do |f| %>
  <div class="form-inputs">
    <%= f.input :url1 %>
    <%= f.input :url2 %>
    <%= f.input :subdomain %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enter your app" %>
  </div>
<% end %>