config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    resources :apps
    resources :invitations, only: [:new, :create]
  end

  root 'pages#index'

  devise_for :users
  resources :invitation_requests, only: [:create,:new]
  namespace :api do
    resources :apps ,only:[:create, :update, :destroy, :index]
    post "/login" => 'users#login'
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="font-size: 30px; font-weight: 600">TheRokuBalance</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="font-size: 20px">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <!--
                <li class="<%= 'active' if params[:controller] == 'invitations' %>">
                  <%= link_to("Invite a friend", new_invitation_path) %>
                </li>
              -->
                <li class="<%= 'active' if(params[:controller] == 'apps') %>">
                  <%= link_to "My apps", apps_path %>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
                    <strong><%= current_user.email %></strong>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to("Sign out", destroy_user_session_path, method: :delete) %></li>
                  </ul>
                </li>
              <% else %>
                <li>
                  <%= link_to "Login", new_user_session_path%>
                </li>
                <li>
                <%= link_to "Sign up", new_user_registration_path %>
                </li>
              <% end %>
            </ul>
        </div>


        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_tutorial.html.erb
<footer class="footer" style="width: 100%; height: 100px; background-color: #2E3234; margin-top: 0px; padding-top: 30px; position: fixed; bottom: 0;">
  <!-- Button trigger modal -->
  <div class="text-center">
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Look at our quick tutorial
    </button>
  </div>

</footer> 
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Quick Setup</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-11 col-md-offset-1">
            <h4>1. Setup both of your heroku servers with the same rails application.</h4>
            <h4>You can do this by getting two heroku repositories:</h4>
            <%= image_tag("git_urls.jpg", :size => "455x82", :alt => "git urls") %>
            <h4>And then adding them to your git remote:</h4>
            <%= image_tag("git_remotes.png", :size => "455x50", :alt => "git remotes") %>
            <h4>Now you can push to each of your heroku remotes:</h4>
            <%= image_tag("git_push.png", :size => "185x50", :alt => "git push") %>
          </div>
          <div class="col-md-10 col-md-offset-1">
            <h4>2. Config both of your repositories so that they're both pointing to the same postgres database, you can do that with the follwing code:</h4>
            <pre><code>$ heroku config | grep DATABASE_URL  --app sushi DATABASE_URL => postgres://database_url
            </code></pre>
            <pre><code>$ heroku config:add DATABASE_URL=postgres://database_url --app sushi-analytics
            </code></pre>
          </div>
          <div class="col-md-10 col-md-offset-1">
            <h4>3. Register on TherokuBalance, install our <a href="https://rubygems.org/gems/theroku">gem theroku</a> and get running fast.</h4>
          </div>
          <div class="col-md-10 col-md-offset-1">
            <h4>4. And that's it! You're all set up. Enjoy.</h4>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheRokuBalance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href="http://red-hat-overpass-fonts.s3.amazonaws.com/overpass.css" rel="stylesheet">
</head>
<body>
  <%= render "layouts/navigation" %>
  <%= yield %>
  <%= render "layouts/tutorial" %>
</body>
</html>